on: push
name: Run tests on Master
jobs:
  ruby25:
    name: Run tests on Ruby 2.5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Install bundler
      run: gem install bundler
    - name: Bundle
      run: bundle install
    - name: RSpec
      run: bundle exec rspec
