on: push
name: Run tests on Master
jobs:
  test:
    name: Run tests
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: RSpec
      uses: skx/github-action-tester@master
